language: ruby
rvm:
  - 1.9.3
  
install: gem install rails
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  
services:
  - redis-server
script:
  - bundle install
  - bundle exec rake "shopqi:bootstrap[mysql]"
deploy:
  provider: openshift
  user: "dwiputra173@gmail.com"
  password: "19091996" # can be encrypted
  domain: "shopify-tarmimi.rhcloud.com"
