language: ruby
rvm:
  - 1.9.3
  
install: gem install rails
addons:
  postgresql: "9.2"
  
services:
  - redis-server
script:
  - bundle install
  - bundle exec rake rake shopqi:bootstrap
deploy:
  provider: openshift
  user: "dwiputra173@gmail.com"
  password: "19091996" # can be encrypted
  domain: "shopify-tarmimi.rhcloud.com"
