language: ruby
rvm:
  - 1.9.3
  
install: gem install rails
addons:
  postgresql: "9.2"
  
services:
  - redis-server
script:
  - bundle install
  - bundle exec rake shopqi:bootstrap
$ travis setup openshift
OpenShift user: dwiputra173@gmail.com
OpenShift password: 19091996
OpenShift application name: |shopify|
OpenShift domain: http://shopify-tarmimi.rhcloud.com/
Deploy only from <dwiputra173@gmail.com>/shopify? |yes| 
Encrypt password? |yes| 
